[project]
name = "agentic-scheduler"
version = "0.1.0"
description = "App to fetch university course info and add into google calendar"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "gradio>=6.2.0",
    "openai>=2.14.0",
    "openai-agents>=0.6.5",
    "playwright>=1.57.0",
]
